app/member/forms.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 09:56:55
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-19 13:04:55
from wtforms import Form, BooleanField, TextField, PasswordField, IntegerField,validators
from wtforms.validators import DataRequired, ValidationError
from flask_wtf.file import FileField, FileAllowed, FileRequired
from app.models import Member, Article
from flask import session, abort

def get_article(id, check_author=True):
	article = Article.query.get(id)
	author = Member.query.get(article.user_id)

	if article is None:
		abort(404, "Article id {} doesn't exist".format(id))

	if check_author and author.id != session['user']:
		abort(403)

	return article

class RegisterForm(Form):
	username = TextField('username', [validators.Required()])
	email = TextField('email', [validators.Email()])
	password = PasswordField('password', [
		validators.Required(),
		validators.EqualTo('password_confirm', message='Passwords must match')
	])
	password_confirm = PasswordField('password_confirm')

	def validate_username(self, field):
		user = Member.query.filter_by(username=field.data).count()
		if user > 0:
			raise ValidationError("username already exists.")


class LoginForm(Form):
	username = TextField('username', [validators.Required()])
	password = PasswordField('password', [validators.Required()])

	def validate_username(self, field):
		user = Member.query.filter_by(username=field.data).count()
		if user == 0:
			raise ValidationError("username does not exist.")


class CreateForm(Form):
	title = TextField('title', [validators.Required()])
	content  = TextField('content',[validators.length(min=10)])

class CommentForm(Form):
	comment = TextField('title', [validators.Required()])
	articleid = IntegerField('articleid')

	def validate_articleid(self, field):
		article = Article.query.filter_by(id=field.data).count()
		if article == 0:
			raise ValidationError("article does not exist.")

class UpdateForm(Form):
	article_id = IntegerField('article_id')
	title = TextField('title', [validators.Required()])
	content  = TextField('content',[validators.length(min=10)])

	def validate_article_id(self, field):
		article = Article.query.get(field.data)
		if article.user_id != session['user']:
			abort(403)
			
class PasswordForm(Form):
	oldpassword = PasswordField('oldpassword')
	newpassword = PasswordField('newpassword', [
		validators.Required(),
		validators.EqualTo('password_confirm', message='Passwords must match')
	])
	password_confirm = PasswordField('password_confirm')


class ModifiyForm(Form):
	username = TextField('username', [validators.Required()])
	signature = TextField('signature')
	email = TextField('signature', [validators.Email()])
	realname = TextField('realname')
	phone = IntegerField('phone', [validators.NumberRange(10000000000,19999999999)])
	address = TextField('realname')


class AvatarForm(Form):
	avatar = FileField("avatar",validators = [FileAllowed(['jpg','png'],'Images Only!'), FileRequired()])

app/member/__init__.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 09:56:46
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-15 19:32:21
from flask import Blueprint

member = Blueprint('member', __name__)

import app.member.views

app/member/views.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 09:57:04
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-21 14:05:14
import functools
import os
from datetime import datetime
from . import member
from flask import render_template, redirect, url_for, session, flash, request
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from app.member.forms import *
from app.models import Member, Article, Comment, Userlog
from app import db, app


def login_required(view):
	@functools.wraps(view)
	def wrapped_view(**kwargs):
		if session.get('user') is None:
			return redirect(url_for('member.login', next= request.url))
		return view(**kwargs)
	return wrapped_view


@member.route('/')
@login_required
def index():
	user = Member.query.get(session['user'])

	return render_template('member/index.html', user=user)



@member.route('/register', methods=('GET','POST'))
def register():
	form = RegisterForm(request.form)
	if request.method == 'POST':
		if form.validate():
			user = Member(
				username = form.username.data,
				email = form.email.data,
				password = generate_password_hash(form.password.data),
				avatar = url_for('static', filename='img/avatars/default.jpg')
			)
			db.session.add(user)
			db.session.commit()
			return redirect(request.args.get('next') or url_for( 'member.login'))

		else:
			flash('may username already exists.')
	return render_template('member/register.html', form=form)



@member.route('/login', methods=('GET', 'POST'))
def login():
	form = LoginForm(request.form)

	if request.method == 'POST' :
		if form.validate():
			user = Member.query.filter_by(username=form.data['username']).first()
			if not user.check_pwd(form.data['password']):
				flash("password error.")
				return render_template('member/login.html')
			session['user'] = user.id
			userlog = Userlog(
				user_id = user.id,
				ip = request.remote_addr
			)
			db.session.add(userlog)
			db.session.commit()
			return redirect(request.args.get('next') or url_for('member.index'))
		else:
			flash('username does not exist.')
		
	return render_template('member/login.html')



@member.route('/logout')
@login_required
def logout():
	session.clear()
	return redirect(url_for('member.index'))



@member.route('/create', methods=('GET', 'POST'))
@login_required
def create():
	form = CreateForm(request.form)

	if request.method == 'POST':
		if form.validate():
			article = Article(
				title = form.data['title'],
				content = form.data['content'],
				addtime = datetime.now(),
				user_id = session['user'],
			)
			db.session.add(article)
			a = db.session.commit()
			return redirect(url_for('member.index'))
		
		flash("Create Error.")
		return render_template('member/create.html')
	else:
		return render_template('member/create.html')


@member.route('/update/<int:id>', methods=('GET', 'POST'))
@login_required
def update(id):
	form = UpdateForm(request.form)
	# print(request.form)
	if request.method == 'POST' and form.validate():
		article = Article.query.filter_by(id=form.data['article_id']).update(
			dict(
				title = form.data['title'],
				content = form.data['content'],
				last_modify = datetime.now()
			)
		)
		db.session.commit()
		new_article = get_article(id)
		return render_template('member/update.html', article=new_article)
	else:
		article = get_article(id)
		return render_template('member/update.html', article=article)



@member.route('/comment', methods=('POST',))
@login_required
def comment():
	form = CommentForm(request.form)
	if form.validate():
		comment = Comment(
			user_id = session['user'],
			article_id = form.data['articleid'],
			content = form.data['comment']
		)
		db.session.add(comment)
		db.session.commit()
		return redirect('article/'+str(form.data['articleid']))
	else:
		flash('comment error')
		return redirect(url_for('blog.article'))

@member.route('/modify', methods=('POST','GET'))
@login_required
def modify():
	form = ModifiyForm(request.form)

	if request.method == 'POST':
		if form.validate():
			user = Member.query.filter_by(id=session['user']).update(
				dict(
					username = form.data['username'],
					signature = form.data['signature'],
					email = form.data['email'],
					realname = form.data['realname'],
					phone = form.data['phone'],
					address = form.data['address'],
				)
			)
			db.session.commit()

		else:
			flash('Incorrect Format.')
	user = Member.query.get(session['user'])

	return render_template('member/modify.html', user=user)


@member.route('/password', methods=('POST','GET'))
@login_required
def password():
	user = Member.query.get(session['user'])
	form = PasswordForm(request.form)
	# print(request.form)
	if request.method== 'POST':
		if form.validate():
			if check_password_hash(user.password, form.data['oldpassword']):

				user = Member.query.filter_by(id=session['user']).update(
					dict( password = generate_password_hash(form.data['newpassword'])))
				db.session.commit()
				return redirect(url_for('member.login'))
			else:
				flash('Old Password Error.')
		else:
			flash('May Passwords not match.')

	return render_template('member/password.html', user=user)


@member.route('/articles')
@login_required
def articles():
	articles = Article.query.filter_by(user_id = session['user']).all()
	return render_template('member/articles.html', articles=articles)


@member.route('/avatar', methods=('POST',))
@login_required
def avatar():
	form = AvatarForm(request.files)
	if form.validate():
		import hashlib
		avatar = form.avatar.data
		filename = secure_filename(avatar.filename)

		ext = os.path.splitext(filename)[1]  #取后缀		
		filename = hashlib.md5(avatar.read()).hexdigest()+ext  #文件哈希
		avatar.seek(0)  #指针重回起点

		file_path = os.path.join(app.config['UPLOAD_FOLDER'],'avatars', filename)
		avatar.save(file_path)


		user = Member.query.filter_by(id=session['user']).update(
			dict(avatar = '/static/img/avatars/'+filename))
		db.session.commit()		

	return redirect(url_for('member.modify'))


@member.route('/userlog')
@login_required
def userlog():
	userlogs = Userlog.query.filter_by(user_id=session['user']).all()
	user = Member.query.get(session['user'])
	return render_template('member/userlog.html', userlogs=userlogs, user=user)

app/templates/member/articles.html
{% extends 'member/member.html' %}

{% block title %}Flask Blog {% endblock %}

{% block div %}



  	{% if articles %}
  	{% for article in articles %}
    <div class="col-md-4 ">
      <h2>{{ article['title'] }}</h2>
      {% if article.content|length > 150 %}
      <p rows="5">{{ article.content[:150] }}.....</p>
      {% else %}
      <p rows="5">{{ article.content }}</p>
      {% endif %}

      <div class="row">
        <div class="col-md-2">
        <p><a class="btn btn-default btn-primary" href="{{ url_for('blog.article', id=article.id) }}" role="button">View Article &raquo;</a></p>
        </div>

        <div class="col-md-1 col-md-offset-7">
        {% if session.get('user').id == article['author_id'] %}
          <p><a class="btn btn-default btn-primary" href="{{ url_for('member.update', id=article.id) }}" role="button">Edit  &raquo;</a></p>
        {% endif %}
        </div>
      </div>

    </div>
    {% endfor %}
    {% endif %}



{% endblock %}

app/templates/member/base.html
{% extends 'base.html' %}

app/templates/member/create.html
{% extends 'member/member.html' %}

{% block title %}Flask Blog {% endblock %}

{% block div %}

<div class="container">
	<div class="row">
	<h2 class="text-center row">Create New Blog</h2>
	<br>
	</div>
		{% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
	<form method="POST">

		<label for="title" class="sr-only">Title</label>
		<input type="text" name="title" class="form-control" placeholder="Title" required>
		<br>
		<label for="content" class="sr-only">Body</label>
		<textarea class="form-control" name="content" rows="15" ></textarea>
		<br>
		<div class="col-lg-offset-11 col-md-offset-11">  
		<button type="submit" class="btn btn-default btn-primary">Submit</button>
		</div>
	</form>
</div>
{% endblock %}

app/templates/member/index.html
{% extends 'member/member.html' %}

{% block div %}
	<div class="row">
	<img src="{{ user.avatar }}" class="img-circle center-block" height="200" width="200"  />
	</div>

	<div class="row">
		<h1 class="text-center row">{{ user.username }}</h1>
	</div>
	<br>
				
	<div class="row">
		<h2 class="text-center row">Signature ： {{ user.signature }}</h2>
	</div>

	<div class="row">
		<h2 class="text-center row">Email ： {{ user.email }}</h2>
	</div>

	<div class="row">
		<h2 class="text-center row">Real-Name ： {{ user.realname }}</h2>
	</div>

	<div class="row">
		<h2 class="text-center row">Phone-number ： {{ user.phone }}</h2>
	</div>
	<div class="row">
		<h2 class="text-center row">Address ： {{ user.address }}</h2>
	</div>


{% endblock %}

app/templates/member/login.html
{% extends 'member/base.html' %}

{% block body %}

    <div class="container">

      <form class="form-signin" method="POST">
        <h2 class="form-signin-heading"><p class="text-primary">Login</p></h2>
        <br>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        <label for="username" class="sr-only">Username</label>
        <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
        <br>
        <label for="password" class="sr-only">Password</label>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <br>

        <button class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
      </form>

    </div> 

{% endblock %}

app/templates/member/member.html
{% extends 'member/base.html' %}

{% block body %}

	<div class="container-fluid">
		<div class="col-sm-3 col-md-2 sidebar">
			<ul class="nav nav-sidebar">
				<li><a class="btn btn-link" href="{{ url_for('member.index') }}">个人资料</a></li>
				<li><a class="btn btn-link" href="{{ url_for('member.modify') }}">修改资料</a></li>
				<li><a class="btn btn-link" href="{{ url_for('member.password') }}">更改密码</a></li>
				<li><a class="btn btn-link" href="{{ url_for('member.articles') }}">个人文章</a></li>
				<li><a class="btn btn-link" href="{{ url_for('member.create') }}">写新文章</a></li>
				<li><a class="btn btn-link" href="{{ url_for('member.userlog') }}">登录日志</a></li>
				
			</ul>
		</div>
		<div class="col-md-10 col-lg-10 jumbotron container ">
			{% block div %}
			{% endblock %}
		</div>
	</div>

{% endblock %}

app/templates/member/modify.html
{% extends 'member/member.html' %}

{% block div %}

	<div class="row">
		<img src="{{ user.avatar }}" class="img-circle center-block" height="200" width="200"  />
		</div>
		<br>


		<div class="row text-center">
			<form action="{{ url_for('member.avatar') }}" method="POST"  enctype="multipart/form-data" >
			<label for="avatar">				
				<input type="file" name="avatar" id="avatar" class="file" >
				<button class="btn btn-lg btn-block btn-primary" type="submit" role="button">Change Avatar</button>
			</label>
			</form>
		</div>
		



		<br>
		<div class="col-lg-8 col-lg-offset-2">
		
		{% for message in get_flashed_messages() %}
	        <div class="alert alert-danger">{{ message }}</div>
	    {% endfor %}
		<form method="POST">
			<div class="row">
				<h3 class="">Username : </h3>
				<input type="text" name="username" class="form-control " value="{{ user.username }}">
			</div>

			<div class="row">
				<h3 class="">Signature : </h3>
				<input type="text" name="signature" class="form-control " value="{% if user.signature != None %}{{ user.signature }}{% else %}{% endif %}">
			</div>
			<div class="row">
				<h3 class="">Email : </h3>
				<input type="email" name="email" class="form-control " value="{{ user.email }}">
			</div>
			<div class="row">
				<h3 class="">Real-name : </h3>
				<input type="text" name="realname" class="form-control " value="{% if user.realname != None %}{{ user.realname }}{% else %}{% endif %}">
			</div>
			<div class="row">
				<h3 class="">Phone-number : </h3>
				<input type="phone" name="phone" class="form-control " value="{% if user.phone != None %}{{ user.phone }}{% else %}{% endif %}">
			</div>
			<div class="row">
				<h3 class="">Address : </h3>
				<input type="text" name="address" class="form-control " value="{% if user.address != None %}{{ user.address }}{% else %}{% endif %}">
			</div>
			<br>
			<button class="btn btn-lg btn-block btn-primary" type="submit" role="button">Save</button>
		</form>

	</div>



{% endblock %}

app/templates/member/password.html
{% extends 'member/member.html' %}

{% block div %}
	<div class="row">
	<img src="{{ user.avatar }}" class="img-circle center-block" height="200" width="200"  />
	</div>
	<div class="row">
		<h1 class="text-center row">{{ user.username }}</h1>
	</div>

	<div class="col-lg-8 col-lg-offset-2">
	{% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
    {% endfor %}
	<form method="POST">

		<div class="row">
			<h3 class="">Old Password : </h3>
			<input type="password" name="oldpassword" class="form-control " value="">
		</div>	
		<div class="row">
			<h3 class="">New Password : </h3>
			<input type="password" name="newpassword" class="form-control " value="">
		</div>

		<div class="row">
			<h3 class="">Reapte Password : </h3>
			<input type="password" name="password_confirm" class="form-control " value="">
		</div>

		<br>
		<button class="btn btn-lg btn-block btn-primary" type="submit" role="button">Change Password</button>
		</div>
	</form>

{% endblock %}

app/templates/member/register.html
{% extends 'member/base.html' %}
{% block body %}
    <div class="container">

      <form class="form-signin" method="POST">
        <h2 class="form-signin-heading"><p class="text-primary">Register</p></h2>
        <br>
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">{{ message }}</div>
        {% endfor %}
        <label for="username" class="sr-only">Username</label>
        <input type="text" name="username" class="form-control" placeholder="Username" required autofocus>
        <br>
        <label for="email" class="sr-only">Email</label>
        <input type="email" name="email" class="form-control" placeholder="Email" required>
        <br>
        <label for="password" class="sr-only">Password</label>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <br>
        <label for="password_confirm" class="sr-only">Password</label>
        <input type="password_confirm" name="password_confirm" class="form-control" placeholder="Password Again" required>
        <br>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
      </form>

    </div> 
{% endblock %}

app/templates/member/update.html
{% extends 'member/base.html' %}

{% block body %}
<div class="container">
	{% for message in get_flashed_messages() %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
	<form method="POST">
		<label for="title" class="sr-only">Title</label>
		<input type="text" name="title" class="form-control" value="{{ article.title }}" required>
		<br>
		<label for="content" class="sr-only">Body</label>
		<textarea class="form-control" name="content" rows="15" >{{ article.content }}</textarea>
		<input type="hidden" name="article_id" value="{{ article.id }}">
		<br>
		<button type="submit" class="btn btn-default btn-primary">Submit</button>
	</form>
	<hr>
	
	<form action="#" method="POST">
		<button type="submit" class="btn btn-default btn-danger" onclick="return confirm('Are you sure?');">Delete</button>	
	</form>

</div>
{% endblock %}

app/templates/member/userlog.html
{% extends 'member/member.html' %}

{% block div %}

	<div class="row">
	<img src="{{ user.avatar }}" class="img-circle center-block" height="200" width="200"  />
	</div>
	<div class="text-center">
      <h2 class="User Log">User Log</h2>
    </div>
    <br>
	  <div class="table-responsive">
	    <table class="table table-striped">
	      <thead>
	        <tr>
	          <th>Login Id</th>
	          <th>Login Ip</th>
	          <th>Login Time</th>
	        </tr>
	      </thead>
	      {% for userlog in userlogs %}
	      <tbody>
	        <tr>
	          <td>{{ loop.index }}</td>
	          <td>{{ userlog.ip }}</td>
	          <td>{{ userlog.addtime }}</td>
	        </tr>
          </tbody>
          {% endfor %}
        </table>
      </div>
    </div>

	{% for userlog in userlogs %}


	{% endfor %}

{% endblock %}