app/blog/forms.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 10:07:56
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-15 10:07:56

app/blog/__init__.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 10:07:38
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-15 19:32:50
from flask import Blueprint

blog = Blueprint('blog', __name__)

import app.blog.views

app/blog/views.py
# -*- coding: utf-8 -*-
# @Author: King kaki
# @Date:   2018-06-15 10:07:47
# @Last Modified by:   King kaki
# @Last Modified time: 2018-06-21 11:06:15
from . import blog
from flask import render_template, redirect, url_for, session, flash, request
from app.models import *

@blog.route('/')
def index():
	articles = Article.query.all()
	return render_template('blog/index.html', articles=articles)


@blog.route('/article/<int:id>')
def article(id):
	article = Article.query.get(id)
	author = Member.query.get(article.user_id)

	click = Article.query.filter_by(id=id).update(dict(click_num = article.click_num+1))
	db.session.commit()
	comments = Comment.query.filter_by(article_id=id).all()
	comments_author=[]
	for comment in comments:
		comments_author.append(Member.query.get(comment.user_id))
	return render_template('blog/article.html', article=article, author=author, comments=comments, comments_author=comments_author)

app/templates/blog/article.html
{% extends 'blog/base.html' %}

{% block body %}

<div class="container col-md-8 col-md-offset-2">
	<div class="text-center  ">
		<h1>{{ article.title }}</h1>
	</div>

	<div class="jumbotron">
		<p>{{ article.content.replace('\r\n','<br>').replace(' ','&nbsp;') | safe}}</p>

	</div>

	<div class="col-md-offset-9">		
		<p>Created by {{ author['username'] }}</p>
		<p>Cilck num : {{ article['click_num'] | default(0) }}</p>
		<p>Created at {{ article.addtime }}</p>
		<p>Last modify {{ article.last_modify }}</p>
	</div>
	<br>
	<h2>留言</h2>
	<form method="POST" action="{{ url_for('member.comment') }}">
	<div class="form-group">
		<input type="hidden" name="articleid" class="form-control" value="{{ article['id'] }}" >
		<label for="comment" class="sr-only">Body</label>
		<textarea class="form-control" name="comment" rows="6" placeholder="Comment"></textarea>
		<br>
		<div class="col-lg-offset-11 col-md-offset-11">  
		<button type="submit" class="btn btn-default btn-primary">Submit</button>
		</div>
	</div>
	</form>

	{% for comment in comments %}
	<hr>
	<div class="container">
		<p>{{ comments_author[loop.index0]['username'] }} :</p>
		<p>{{ comment.content }}</p>
		<p>{{ comment.addtime }}</p>
	</div>
	{% endfor %}


</div>

{% endblock %}

app/templates/blog/base.html
{% extends 'base.html' %}

app/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block title %}Flask Blog {% endblock %}

{% block body %}

<div class="container">

  	{% if articles %}
  	{% for article in articles %}
    <div class="col-md-4 ">
      <h2>{{ article['title'] }}</h2>
      {% if article.content|length > 150 %}
      <p rows="5">{{ article.content[:150] }}.....</p>
      {% else %}
      <p rows="5">{{ article.content }}</p>
      {% endif %}

      <div class="row">
        <div class="col-md-2">
        <p><a class="btn btn-default btn-primary" href="{{ url_for('blog.article', id=article.id) }}" role="button">View Article &raquo;</a></p>
        </div>

        <div class="col-md-1 col-md-offset-7">
        {% if session['user'].id == article['author_id'] %}
          <p><a class="btn btn-default btn-primary" href="{{ url_for('member.update', id=article.id) }}" role="button">Edit  &raquo;</a></p>
        {% endif %}
        </div>
      </div>

    </div>
    {% endfor %}
    {% endif %}

  </div>


{% endblock %}